### ISSUE TITLE
Misc cleanup: remove .editorconfig and vim style in bin/airtap.js

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#72]

**Comment by yeskunall** [comment]
Do you mean the `.editorconfig` at the root of the repo? If so, I think that should stay. It helps devs maintain consistent coding styles between different editors.

**Comment by ralphtheninja** [comment]
We don't need that since we have `standard`?

**Comment by yeskunall** [comment]
Aww, shucks. I've been misinformed. I really need to read up more on StandardJS. 😓 I'll take this up, if it's all right with you!

**Comment by feross** [comment]
Some people say that `.editorconfig` is still useful even with `standard` since some editors will read it and automatically set the right indentation settings, etc.

I've never found it useful and always delete it where I find it, but I guess I don't jump between projects with different code styles very often. So `standard` alone is enough for me.
